name: Main Pipeline
on:
  workflow_run:
    workflows: [tfsec]
    types: 
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.

          on-failure: true
          runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
          
      - run: echo 'The triggering workflow failed'
   
   



















