name: Main Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check terraform configuration
      uses: ./.github/workflows/tfsec_pr_commenter.yml
      
    - name: Check repo for secrets
      if: success()
      uses: ./.github/workflows/gitleaks_secrets_checker.yml
