name: Dependencies
on:
  push:
    branches: ["statistics"]
  pull_request:
    branches: ["main"]
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
jobs:
  tfsec:
    name: TFSEC_Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}

  build-environment-and-function-app:
    name: Setup DotNet Environment and build function
    needs: [tfsec]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.402
      - name: Build Azure Function App
        shell: bash
        run: |
          pushd './functionApp'
          dotnet build --configuration Release --output ./output
          popd